# Generated by Django 4.2.4 on 2023-09-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='tax_id',
            field=models.IntegerField(verbose_name='ИНН'),
        ),
    ]
