# Generated by Django 4.2.4 on 2023-09-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_version_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='is_active',
            field=models.CharField(choices=[('YES', 'ДА'), ('NO', 'НЕТ')], default='NO', verbose_name='Текущая'),
        ),
    ]
