# Generated by Django 4.2.4 on 2023-09-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_version_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='is_active',
            field=models.BooleanField(default='False', verbose_name='Текущая'),
        ),
        migrations.AlterField(
            model_name='version',
            name='num',
            field=models.IntegerField(auto_created=True, verbose_name='Номер'),
        ),
    ]
