# Generated by Django 4.2.4 on 2023-09-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_version_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='num',
            field=models.IntegerField(auto_created=True, blank=True, null=True, verbose_name='Номер'),
        ),
    ]
